// Grammar and Spelling Correction Dataset
const GRAMMAR_DATA = {
    // Common spelling corrections (500+ entries)
    spelling: {
        // A
        "abandonned": "abandoned",
        "aberation": "aberration",
        "abilty": "ability",
        "ananimus":"anonymus",
        "abscence": "absence",
        "absense": "absence",
        "absolutly": "absolutely",
        "accademic": "academic",
        "accellerate": "accelerate",
        "acceptible": "acceptable",
        "accesible": "accessible",
        "accidently": "accidentally",
        "accomodate": "accommodate",
        "acommodate": "accommodate",
        "accompany": "accompany",
        "accordian": "accordion",
        "accross": "across",
        "acheive": "achieve",
        "achive": "achieve",
        "acknowlege": "acknowledge",
        "acknowlegement": "acknowledgement",
        "acquaintence": "acquaintance",
        "acquaintance": "acquaintance",
        "acquited": "acquitted",
        "addictoin": "addiction",
        "addres": "address",
        "adress": "address",
        "advertisment": "advertisement",
        "advise": "advice",
        "aeroplane": "airplane",
        "afair": "affair",
        "afficionado": "aficionado",
        "agressive": "aggressive",
        "agression": "aggression",
        "alchohol": "alcohol",
        "alchol": "alcohol",
        "allready": "already",
        "alot": "a lot",
        "alright": "all right",
        "altho": "although",
        "amature": "amateur",
        "amashing": "amazing",
        "amzing": "amazing",
        "amazng": "amazing",
        "aniversary": "anniversary",
        "annonymous": "anonymous",
        "anual": "annual",
        "aparent": "apparent",
        "aparment": "apartment",
        "apear": "appear",
        "appearence": "appearance",
        "applause": "applause",
        "apreciate": "appreciate",
        "apropriate": "appropriate",
        "aquire": "acquire",
        "arguement": "argument",
        "artic": "arctic",
        "artical": "article",
        "asthetic": "aesthetic",
        "athiest": "atheist",
        "atheletic": "athletic",
        "attatch": "attach",
        "attemp": "attempt",
        "attendence": "attendance",
        "auther": "author",
        "availible": "available",
        "awsome": "awesome",
        
        // B
        "basicaly": "basically",
        "beacuse": "because",
        "becaus": "because",
        "becuase": "because",
        "becouse": "because",
        "becasue": "because",
        "becuze": "because",
        "befor": "before",
        "begining": "beginning",
        "beleive": "believe",
        "belive": "believe",
        "beleve": "believe",
        "benfit": "benefit",
        "beutiful": "beautiful",
        "bizzare": "bizarre",
        "boundry": "boundary",
        "breif": "brief",
        "brillant": "brilliant",
        "buisness": "business",
        "bussiness": "business",
        "busness": "business",
        
        // C
        "calander": "calendar",
        "calender": "calendar",
        "camoflage": "camouflage",
        "campain": "campaign",
        "carefull": "careful",
        "carrer": "career",
        "catagory": "category",
        "cemetary": "cemetery",
        "cemetry": "cemetery",
        "centuary": "century",
        "ceratin": "certain",
        "certian": "certain",
        "changable": "changeable",
        "charachter": "character",
        "cheif": "chief",
        "choise": "choice",
        "cieling": "ceiling",
        "circut": "circuit",
        "clarifiation": "clarification",
        "collegue": "colleague",
        "colum": "column",
        "comming": "coming",
        "commitee": "committee",
        "committe": "committee",
        "compair": "compare",
        "compatable": "compatible",
        "competant": "competent",
        "compleatly": "completely",
        "concious": "conscious",
        "concensus": "consensus",
        "concieted": "conceited",
        "conection": "connection",
        "confindence": "confidence",
        "congradulations": "congratulations",
        "conquer": "conquer",
        "consciense": "conscience",
        "consious": "conscious",
        "contraversy": "controversy",
        "convience": "convenience",
        "coresponding": "corresponding",
        "critisism": "criticism",
        "curiousity": "curiosity",
        
        // D
        "decison": "decision",
        "definate": "definite",
        "definately": "definitely",
        "definatly": "definitely",
        "defintely": "definitely",
        "defintly": "definitely",
        "defiantly": "definitely",
        "delicious": "delicious",
        "dependant": "dependent",
        "desicion": "decision",
        "desparate": "desperate",
        "deterant": "deterrent",
        "develope": "develop",
        "developement": "development",
        "diference": "difference",
        "diffrent": "different",
        "dilema": "dilemma",
        "dinning": "dining",
        "disapear": "disappear",
        "disapoint": "disappoint",
        "disasterous": "disastrous",
        "discription": "description",
        "disobediance": "disobedience",
        "doesnt": "doesn't",
        "dont": "don't",
        "droped": "dropped",
        
        // E
        "ecstacy": "ecstasy",
        "efficency": "efficiency",
        "eigth": "eighth",
        "embarass": "embarrass",
        "embaress": "embarrass",
        "emergancy": "emergency",
        "emmediately": "immediately",
        "envirornment": "environment",
        "enviornment": "environment",
        "enviroment": "environment",
        "equiped": "equipped",
        "equiptment": "equipment",
        "esential": "essential",
        "exagerate": "exaggerate",
        "excelent": "excellent",
        "excercise": "exercise",
        "excitment": "excitement",
        "existance": "existence",
        "experiance": "experience",
        "expierence": "experience",
        "explaination": "explanation",
        "extention": "extension",
        "extremly": "extremely",
        
        // F
        "facinating": "fascinating",
        "familar": "familiar",
        "famouse": "famous",
        "febuary": "February",
        "fiery": "fiery",
        "finaly": "finally",
        "florescent": "fluorescent",
        "foriegn": "foreign",
        "foward": "forward",
        "fourty": "forty",
        "freind": "friend",
        "frend": "friend",
        "freindly": "friendly",
        "fullfil": "fulfill",
        "futher": "further",
        
        // G
        "goverment": "government",
        "govenment": "government",
        "goverment": "government",
        "gratefull": "grateful",
        "greatful": "grateful",
        "grammer": "grammar",
        "guarentee": "guarantee",
        "gaurd": "guard",
        "guidence": "guidance",
        
        // H
        "harrass": "harass",
        "heigth": "height",
        "hieght": "height",
        "hierachy": "hierarchy",
        "higeine": "hygiene",
        "hopefull": "hopefully",
        "humerous": "humorous",
        "hygeine": "hygiene",
        
        // I
        "identicle": "identical",
        "ignorence": "ignorance",
        "imediately": "immediately",
        "immediatly": "immediately",
        "incidently": "incidentally",
        "independant": "independent",
        "indispensible": "indispensable",
        "infomation": "information",
        "innoculate": "inoculate",
        "inteligence": "intelligence",
        "inteligent": "intelligent",
        "intresting": "interesting",
        "irresistable": "irresistible",
        "irrelevent": "irrelevant",
        
        // J-K
        "jelousy": "jealousy",
        "jewelery": "jewelry",
        "judgement": "judgment",
        "knowlege": "knowledge",
        
        // L
        "labratory": "laboratory",
        "layed": "laid",
        "lenght": "length",
        "liason": "liaison",
        "libary": "library",
        "libery": "liberty",
        "licience": "license",
        "lightening": "lightning",
        "liesure": "leisure",
        "lisence": "license",
        "loose": "lose",
        
        // M
        "maintainance": "maintenance",
        "managment": "management",
        "marraige": "marriage",
        "mathmatics": "mathematics",
        "medecine": "medicine",
        "memeber": "member",
        "millenium": "millennium",
        "minature": "miniature",
        "minit": "minute",
        "mischevious": "mischievous",
        "moive": "movie",
        "movei": "movie",
        "mussle": "muscle",
        
        // N
        "naturaly": "naturally",
        "neccessary": "necessary",
        "neccesary": "necessary",
        "necesary": "necessary",
        "neice": "niece",
        "nieghbor": "neighbor",
        "nineth": "ninth",
        "noticable": "noticeable",
        "nucular": "nuclear",
        
        // O
        "ocasion": "occasion",
        "occassion": "occasion",
        "occured": "occurred",
        "occuring": "occurring",
        "occurence": "occurrence",
        "offence": "offense",
        "omision": "omission",
        "opertunity": "opportunity",
        "oppurtunity": "opportunity",
        "orignal": "original",
        "outragous": "outrageous",
        
        // P
        "paralel": "parallel",
        "parlament": "parliament",
        "particulary": "particularly",
        "sudocode":"pseudocode",
        "passtime": "pastime",
        "peacefull": "peaceful",
        "peice": "piece",
        "peopel": "people",
        "poeple": "people",
        "pepole": "people",
        "peple": "people",
        "platfarm":"platform",
        "plantz":"plants",
        "perfomance": "performance",
        "permanant": "permanent",
        "perseverence": "perseverance",
        "personaly": "personally",
        "persaude": "persuade",
        "phisical": "physical",
        "playright": "playwright",
        "politican": "politician",
        "posession": "possession",
        "possable": "possible",
        "potatos": "potatoes",
        "practicaly": "practically",
        "prefered": "preferred",
        "prejudice": "prejudice",
        "presance": "presence",
        "privelege": "privilege",
        "probaly": "probably",
        "profesional": "professional",
        "promiss": "promise",
        "pronounciation": "pronunciation",
        "psycology": "psychology",
        "publically": "publicly",
        "puting": "putting",
        
        // Q-R
        "quesiton": "question",
        "questionaire": "questionnaire",
        "reccomend": "recommend",
        "recieve": "receive",
        "recieves": "receives",
        "recieved": "received",
        "recieving": "receiving",
        "reconize": "recognize",
        "refered": "referred",
        "relevent": "relevant",
        "religous": "religious",
        "remeber": "remember",
        "repitition": "repetition",
        "resistence": "resistance",
        "responsability": "responsibility",
        "resturant": "restaurant",
        "rythm": "rhythm",
        "rythym": "rhythm",
        
        // S
        "sacrafice": "sacrifice",
        "safty": "safety",
        "scedule": "schedule",
        "sciense": "science",
        "secratary": "secretary",
        "seperate": "separate",
        "seperating": "separating",
        "seperated": "separated",
        "sergant": "sergeant",
        "shinning": "shining",
        "sieze": "seize",
        "similiar": "similar",
        "sinceerly": "sincerely",
        "skillfull": "skillful",
        "speach": "speech",
        "stoping": "stopping",
        "strenght": "strength",
        "studing": "studying",
        "succesful": "successful",
        "sucess": "success",
        "sucessful": "successful",
        "supercede": "supersede",
        "suprise": "surprise",
        "surley": "surely",
        "symetry": "symmetry",
        
        // T
        "temperture": "temperature",
        "tendancy": "tendency",
        "thier": "their",
        "thieves": "thieves",
        "thorough": "thorough",
        "tommorow": "tomorrow",
        "tomorow": "tomorrow",
        "tounge": "tongue",
        "truely": "truly",
        "twelth": "twelfth",
        "tyrany": "tyranny",
        
        // U-V
        "undoubtably": "undoubtedly",
        "unfortunatly": "unfortunately",
        "untill": "until",
        "usefull": "useful",
        "usualy": "usually",
        "vaccuum": "vacuum",
        "vegatarian": "vegetarian",
        "vehical": "vehicle",
        "visable": "visible",
        
        // W-Z
        "wander": "wonder",
        "weath": "weather",
        "weigth": "weight",
        "wellcome": "welcome",
        "wheter": "whether",
        "wich": "which",
        "wierd": "weird",
        "wieght": "weight",
        "writting": "writing",
        "yatch": "yacht",
        "yeild": "yield"
    },

    // Contractions without apostrophes (50+ entries)
    contractions: {
        "arent": "aren't",
        "cant": "can't",
        "couldnt": "couldn't",
        "didnt": "didn't",
        "doesnt": "doesn't",
        "dont": "don't",
        "hadnt": "hadn't",
        "hasnt": "hasn't",
        "havent": "haven't",
        "hes": "he's",
        "heres": "here's",
        "hows": "how's",
        "id": "I'd",
        "ill": "I'll",
        "im": "I'm",
        "isnt": "isn't",
        "itd": "it'd",
        "itll": "it'll",
        "its": "it's",
        "ive": "I've",
        "lets": "let's",
        "mustnt": "mustn't",
        "neednt": "needn't",
        "shant": "shan't",
        "shed": "she'd",
        "shell": "she'll",
        "shes": "she's",
        "shouldnt": "shouldn't",
        "thatd": "that'd",
        "thatll": "that'll",
        "thats": "that's",
        "thered": "there'd",
        "therell": "there'll",
        "theres": "there's",
        "theyd": "they'd",
        "theyll": "they'll",
        "theyre": "they're",
        "theyve": "they've",
        "wasnt": "wasn't",
        "wed": "we'd",
        "well": "we'll",
        "were": "we're",
        "werent": "weren't",
        "weve": "we've",
        "whats": "what's",
        "whens": "when's",
        "wheres": "where's",
        "whos": "who's",
        "whys": "why's",
        "wont": "won't",
        "wouldnt": "wouldn't",
        "youd": "you'd",
        "youll": "you'll",
        "youre": "you're",
        "youve": "you've"
    },

    // Common phrase corrections (100+ entries)
    phrases: {
        // Could/Would/Should of
        "could of": "could have",
        "would of": "would have",
        "should of": "should have",
        "might of": "might have",
        "must of": "must have",
        "ought of": "ought to have",
        
        // Your/You're confusion
        "your welcome": "you're welcome",
        "your right": "you're right",
        "your wrong": "you're wrong",
        "your late": "you're late",
        "your early": "you're early",
        "your awesome": "you're awesome",
        "your amazing": "you're amazing",
        "your beautiful": "you're beautiful",
        "your smart": "you're smart",
        "your funny": "you're funny",
        "your crazy": "you're crazy",
        "your perfect": "you're perfect",
        "your special": "you're special",
        "your invited": "you're invited",
        "your hired": "you're hired",
        "your fired": "you're fired",
        "your kidding": "you're kidding",
        "your joking": "you're joking",
        "your lying": "you're lying",
        "your missing": "you're missing",
        "your coming": "you're coming",
        "your going": "you're going",
        "your leaving": "you're leaving",
        "your staying": "you're staying",
        "your working": "you're working",
        "your sleeping": "you're sleeping",
        "your eating": "you're eating",
        "your drinking": "you're drinking",
        "your reading": "you're reading",
        "your writing": "you're writing",
        "your thinking": "you're thinking",
        "your feeling": "you're feeling",
        "your looking": "you're looking",
        "your listening": "you're listening",
        "your talking": "you're talking",
        "your walking": "you're walking",
        "your running": "you're running",
        "your driving": "you're driving",
        "your flying": "you're flying",
        "your swimming": "you're swimming",
        "your dancing": "you're dancing",
        "your singing": "you're singing",
        "your playing": "you're playing",
        
        // Their/There/They're confusion
        "their is": "there is",
        "their are": "there are",
        "their was": "there was",
        "their were": "there were",
        "their will be": "there will be",
        "their would be": "there would be",
        "their should be": "there should be",
        "their could be": "there could be",
        "their might be": "there might be",
        "their must be": "there must be",
        "their has been": "there has been",
        "their have been": "there have been",
        "their had been": "there had been",
        "their seems to be": "there seems to be",
        "their appears to be": "there appears to be",
        "their exists": "there exists",
        "their remains": "there remains",
        "their stands": "there stands",
        "their lies": "there lies",
        "their sits": "there sits",
        "their goes": "there goes",
        "their comes": "there comes",
        
        // Its/It's confusion
        "its a": "it's a",
        "its an": "it's an",
        "its been": "it's been",
        "its not": "it's not",
        "its never": "it's never",
        "its always": "it's always",
        "its really": "it's really",
        "its very": "it's very",
        "its quite": "it's quite",
        "its pretty": "it's pretty",
        "its so": "it's so",
        "its too": "it's too",
        "its also": "it's also",
        "its still": "it's still",
        "its already": "it's already",
        "its just": "it's just",
        "its only": "it's only",
        "its about": "it's about",
        "its like": "it's like",
        "its time": "it's time",
        "its over": "it's over",
        "its done": "it's done",
        "its finished": "it's finished",
        "its ready": "it's ready",
        "its perfect": "it's perfect",
        "its amazing": "it's amazing",
        "its awesome": "it's awesome",
        "its great": "it's great",
        "its good": "it's good",
        "its bad": "it's bad",
        "its terrible": "it's terrible",
        "its horrible": "it's horrible",
        "its wonderful": "it's wonderful",
        "its beautiful": "it's beautiful",
        "its ugly": "it's ugly",
        "its hot": "it's hot",
        "its cold": "it's cold",
        "its warm": "it's warm",
        "its cool": "it's cool",
        "its big": "it's big",
        "its small": "it's small",
        "its huge": "it's huge",
        "its tiny": "it's tiny",
        "its fast": "it's fast",
        "its slow": "it's slow",
        "its easy": "it's easy",
        "its hard": "it's hard",
        "its difficult": "it's difficult",
        "its simple": "it's simple",
        "its complicated": "it's complicated",
        "its important": "it's important",
        "its necessary": "it's necessary",
        "its possible": "it's possible",
        "its impossible": "it's impossible"
    },

    // Formal tone replacements (150+ entries)
    formal: {
        // Casual contractions to formal
        "gonna": "going to",
        "wanna": "want to",
        "gotta": "have to",
        "hafta": "have to",
        "shoulda": "should have",
        "coulda": "could have",
        "woulda": "would have",
        "kinda": "kind of",
        "sorta": "sort of",
        "lotta": "lot of",
        "dunno": "do not know",
        "lemme": "let me",
        "gimme": "give me",
        "betcha": "bet you",
        "gotcha": "got you",
        "whatcha": "what are you",
        "howdy": "hello",
        
        // Casual responses to formal
        "yeah": "yes",
        "yep": "yes",
        "yup": "yes",
        "uh-huh": "yes",
        "nope": "no",
        "nah": "no",
        "uh-uh": "no",
        "ok": "acceptable",
        "okay": "acceptable",
        "alright": "acceptable",
        "sure": "certainly",
        "cool": "acceptable",
        "awesome": "excellent",
        "great": "excellent",
        "nice": "pleasant",
        "sweet": "excellent",
        "sick": "excellent",
        "dope": "excellent",
        "lit": "excellent",
        "fire": "excellent",
        
        // Casual words to formal
        "got to": "must",
        "have to": "must",
        "need to": "should",
        "a lot of": "many",
        "lots of": "numerous",
        "tons of": "numerous",
        "loads of": "numerous",
        "heaps of": "numerous",
        "bunch of": "several",
        "guys": "individuals",
        "folks": "people",
        "peeps": "people",
        "dudes": "individuals",
        "ladies": "women",
        "gents": "gentlemen",
        "kids": "children",
        "stuff": "items",
        "things": "items",
        "junk": "items",
        "gear": "equipment",
        "kit": "equipment",
        
        // Casual verbs to formal
        "get": "obtain",
        "grab": "obtain",
        "snag": "obtain",
        "nab": "obtain",
        "pick up": "acquire",
        "show": "demonstrate",
        "tell": "inform",
        "say": "state",
        "talk": "communicate",
        "chat": "converse",
        "speak": "communicate",
        "help": "assist",
        "aid": "assist",
        "back up": "support",
        "ask": "inquire",
        "question": "inquire",
        "buy": "purchase",
        "sell": "market",
        "trade": "exchange",
        "swap": "exchange",
        "give": "provide",
        "hand over": "provide",
        "take": "receive",
        "grab": "seize",
        "start": "commence",
        "begin": "commence",
        "kick off": "initiate",
        "launch": "initiate",
        "end": "conclude",
        "finish": "complete",
        "wrap up": "conclude",
        "stop": "cease",
        "quit": "discontinue",
        "drop": "discontinue",
        "ditch": "abandon",
        "dump": "discard",
        "toss": "discard",
        "chuck": "discard",
        "fix": "repair",
        "mend": "repair",
        "patch": "repair",
        "break": "damage",
        "smash": "destroy",
        "wreck": "destroy",
        "ruin": "destroy",
        "mess up": "damage",
        "screw up": "damage",
        "blow": "fail",
        "bomb": "fail",
        "flop": "fail",
        "tank": "fail",
        "crash": "fail",
        "nail": "succeed",
        "ace": "excel",
        "rock": "excel",
        "kill": "excel",
        "slay": "excel",
        "crush": "excel",
        "dominate": "excel",
        "own": "excel",
        "boss": "manage",
        "run": "manage",
        "handle": "manage",
        "deal with": "address",
        "tackle": "address",
        "sort out": "resolve",
        "figure out": "determine",
        "work out": "resolve",
        "check out": "examine",
        "look at": "examine",
        "peek at": "examine",
        "glance at": "observe",
        "eye": "observe",
        "spot": "notice",
        "catch": "notice",
        "see": "observe",
        "watch": "observe",
        "view": "observe",
        "hear": "listen",
        "listen to": "attend",
        "tune in": "attend",
        "zone out": "ignore",
        "space out": "ignore",
        "blank out": "ignore",
        "black out": "lose consciousness",
        "pass out": "lose consciousness",
        "knock out": "render unconscious",
        "wake up": "awaken",
        "get up": "arise",
        "stand up": "arise",
        "sit down": "be seated",
        "lie down": "recline",
        "chill": "relax",
        "hang out": "socialize",
        "hook up": "connect",
        "link up": "connect",
        "team up": "collaborate",
        "pair up": "partner",
        "split up": "separate",
        "break up": "separate",
        "make up": "reconcile",
        "patch up": "reconcile",
        "kiss up": "flatter",
        "suck up": "flatter",
        "brown nose": "flatter",
        "butter up": "flatter",
        "sweet talk": "persuade",
        "smooth talk": "persuade",
        "talk into": "persuade",
        "talk out of": "dissuade",
        "freak out": "panic",
        "flip out": "become upset",
        "bug out": "leave quickly",
        "bail out": "abandon",
        "cop out": "avoid responsibility",
        "wimp out": "withdraw",
        "chicken out": "withdraw",
        "back out": "withdraw",
        "opt out": "withdraw",
        "drop out": "withdraw",
        "phase out": "eliminate gradually",
        "fade out": "disappear gradually",
        "black out": "censor",
        "white out": "erase",
        "cross out": "delete",
        "scratch out": "delete",
        "rub out": "erase",
        "wipe out": "eliminate",
        "take out": "remove",
        "cut out": "eliminate",
        "leave out": "omit",
        "rule out": "exclude",
        "count out": "exclude",
        "write off": "dismiss",
        "blow off": "ignore",
        "brush off": "dismiss",
        "shrug off": "dismiss",
        "laugh off": "dismiss",
        "play down": "minimize",
        "tone down": "moderate",
        "calm down": "relax",
        "cool down": "relax",
        "slow down": "decelerate",
        "speed up": "accelerate",
        "hurry up": "accelerate",
        "step up": "increase",
        "ramp up": "increase",
        "pump up": "increase",
        "beef up": "strengthen",
        "bulk up": "increase size",
        "build up": "develop",
        "work up": "develop",
        "stir up": "provoke",
        "whip up": "create quickly",
        "cook up": "devise",
        "dream up": "imagine",
        "make up": "invent",
        "come up": "approach",
        "show up": "appear",
        "turn up": "appear",
        "pop up": "appear suddenly",
        "spring up": "emerge",
        "crop up": "arise",
        "bring up": "mention",
        "bring out": "reveal",
        "point out": "indicate",
        "spell out": "explain clearly",
        "lay out": "arrange",
        "set out": "arrange",
        "put out": "extinguish",
        "put up": "tolerate",
        "put down": "criticize",
        "put off": "postpone",
        "put on": "wear",
        "take off": "remove",
        "take on": "accept",
        "take up": "begin",
        "take in": "absorb",
        "take over": "assume control",
        "take back": "retract",
        "give up": "surrender",
        "give in": "surrender",
        "give out": "distribute",
        "give back": "return",
        "give away": "donate",
        "throw away": "discard",
        "throw out": "discard",
        "throw up": "vomit",
        "throw in": "include",
        "throw off": "confuse",
        "throw back": "return",
        "send back": "return",
        "send out": "distribute",
        "send off": "dispatch",
        "send up": "mock",
        "send down": "expel",
        "call back": "return call",
        "call out": "challenge",
        "call off": "cancel",
        "call up": "telephone",
        "call in": "summon",
        "call for": "require",
        "look up": "research",
        "look out": "be careful",
        "look into": "investigate",
        "look over": "examine",
        "look after": "care for",
        "look down on": "despise",
        "look up to": "admire",
        "look forward to": "anticipate",
        "look back on": "remember",
        "go back": "return",
        "go out": "exit",
        "go up": "ascend",
        "go down": "descend",
        "go in": "enter",
        "go over": "review",
        "go through": "experience",
        "go with": "accompany",
        "go without": "do without",
        "go for": "attempt",
        "go against": "oppose",
        "come back": "return",
        "come out": "emerge",
        "come up": "approach",
        "come down": "descend",
        "come in": "enter",
        "come over": "visit",
        "come through": "succeed",
        "come with": "accompany",
        "come without": "arrive unaccompanied",
        "come for": "retrieve",
        "come against": "oppose"
    },

    // Friendly tone replacements (100+ entries)
    friendly: {
        // Formal to casual verbs
        "purchase": "buy",
        "obtain": "get",
        "acquire": "get",
        "receive": "get",
        "retrieve": "get",
        "procure": "get",
        "secure": "get",
        "assist": "help",
        "aid": "help",
        "support": "back up",
        "facilitate": "help",
        "enable": "help",
        "inquire": "ask",
        "request": "ask for",
        "solicit": "ask for",
        "petition": "ask",
        "query": "ask",
        "interrogate": "question",
        "commence": "start",
        "initiate": "start",
        "begin": "start",
        "launch": "kick off",
        "establish": "set up",
        "institute": "set up",
        "conclude": "end",
        "terminate": "end",
        "finalize": "finish",
        "complete": "finish",
        "accomplish": "do",
        "achieve": "pull off",
        "attain": "reach",
        "demonstrate": "show",
        "exhibit": "show",
        "display": "show",
        "present": "show",
        "reveal": "show",
        "illustrate": "show",
        "utilize": "use",
        "employ": "use",
        "apply": "use",
        "implement": "use",
        "operate": "run",
        "execute": "do",
        "perform": "do",
        "conduct": "do",
        "carry out": "do",
        "undertake": "take on",
        "endeavor": "try",
        "attempt": "try",
        "strive": "try hard",
        "struggle": "fight",
        "compete": "go up against",
        "contest": "challenge",
        "dispute": "argue about",
        "debate": "argue about",
        "discuss": "talk about",
        "converse": "chat",
        "communicate": "talk",
        "correspond": "write to",
        "contact": "get in touch with",
        "approach": "come up to",
        "address": "talk to",
        "greet": "say hi to",
        "salute": "say hi to",
        "acknowledge": "recognize",
        "recognize": "spot",
        "identify": "figure out",
        "determine": "figure out",
        "establish": "figure out",
        "ascertain": "find out",
        "discover": "find out",
        "uncover": "find out",
        "detect": "spot",
        "locate": "find",
        "position": "put",
        "place": "put",
        "situate": "put",
        "install": "put in",
        "insert": "put in",
        "introduce": "bring in",
        "incorporate": "work in",
        "integrate": "blend in",
        "combine": "mix",
        "merge": "blend",
        "unite": "join",
        "connect": "link up",
        "attach": "hook up",
        "fasten": "tie",
        "secure": "tie down",
        "fix": "repair",
        "mend": "fix",
        "restore": "fix up",
        "renovate": "fix up",
        "refurbish": "spruce up",
        "improve": "make better",
        "enhance": "boost",
        "upgrade": "beef up",
        "advance": "move forward",
        "progress": "move ahead",
        "proceed": "go ahead",
        "continue": "keep going",
        "persist": "keep at it",
        "persevere": "stick with it",
        "endure": "put up with",
        "tolerate": "put up with",
        "accept": "go with",
        "approve": "give thumbs up",
        "authorize": "give the ok",
        "permit": "let",
        "allow": "let",
        "enable": "let",
        "facilitate": "make easy",
        "simplify": "make easy",
        "clarify": "clear up",
        "explain": "spell out",
        "describe": "tell about",
        "narrate": "tell",
        "relate": "tell",
        "report": "tell about",
        "inform": "let know",
        "notify": "let know",
        "alert": "warn",
        "warn": "heads up",
        "caution": "watch out",
        "advise": "tell",
        "recommend": "suggest",
        "propose": "suggest",
        "suggest": "throw out",
        "indicate": "point to",
        "specify": "spell out",
        "designate": "pick",
        "select": "pick",
        "choose": "go with",
        "decide": "make up mind",
        "resolve": "sort out",
        "settle": "work out",
        "arrange": "set up",
        "organize": "set up",
        "prepare": "get ready",
        "plan": "map out",
        "schedule": "set up",
        "coordinate": "sync up",
        "synchronize": "sync up",
        "align": "line up",
        "adjust": "tweak",
        "modify": "change",
        "alter": "change",
        "transform": "change",
        "convert": "turn into",
        "translate": "turn into",
        "interpret": "make sense of",
        "understand": "get",
        "comprehend": "get",
        "grasp": "get",
        "perceive": "see",
        "observe": "watch",
        "witness": "see",
        "notice": "spot",
        "regard": "see as",
        "consider": "think about",
        "contemplate": "think over",
        "ponder": "think about",
        "reflect": "think back",
        "remember": "think back to",
        "recall": "think back to",
        "recollect": "remember",
        "reminisce": "think back",
        "forget": "blank on",
        "ignore": "blow off",
        "disregard": "blow off",
        "overlook": "miss",
        "neglect": "skip",
        "abandon": "ditch",
        "desert": "bail on",
        "leave": "take off",
        "depart": "head out",
        "exit": "get out",
        "escape": "get away",
        "flee": "run away",
        "retreat": "back off",
        "withdraw": "pull back",
        "return": "come back",
        "arrive": "show up",
        "appear": "show up",
        "emerge": "come out",
        "surface": "come up",
        "arise": "come up",
        "occur": "happen",
        "happen": "go down",
        "transpire": "go down",
        "develop": "come about",
        "evolve": "grow into",
        "mature": "grow up",
        "expand": "grow",
        "increase": "go up",
        "decrease": "go down",
        "reduce": "cut down",
        "minimize": "cut down",
        "maximize": "pump up",
        "optimize": "fine-tune",
        "perfect": "nail",
        "excel": "rock",
        "succeed": "make it",
        "triumph": "win big",
        "prevail": "come out on top",
        "dominate": "rule",
        "control": "run",
        "manage": "handle",
        "supervise": "keep an eye on",
        "oversee": "watch over",
        "monitor": "keep tabs on",
        "track": "follow",
        "pursue": "go after",
        "chase": "run after",
        "hunt": "go after",
        "search": "look for",
        "seek": "look for",
        "explore": "check out",
        "investigate": "look into",
        "examine": "check out",
        "inspect": "look over",
        "review": "go over",
        "analyze": "break down",
        "evaluate": "size up",
        "assess": "check out",
        "judge": "size up",
        "criticize": "rip apart",
        "praise": "give props",
        "compliment": "say nice things",
        "congratulate": "give props",
        "celebrate": "party",
        "enjoy": "have fun with",
        "appreciate": "dig",
        "admire": "look up to",
        "respect": "look up to",
        "honor": "give props to",
        "worship": "look up to big time",
        "adore": "love",
        "cherish": "treasure",
        "treasure": "hold dear",
        "value": "think highly of",
        "prize": "treasure",
        "esteem": "think highly of"
    },

    // Clarity improvements (100+ entries)
    clarity: {
        // Wordy phrases to clear alternatives
        "in spite of the fact that": "although",
        "despite the fact that": "although",
        "notwithstanding the fact that": "although",
        "regardless of the fact that": "although",
        "due to the fact that": "because",
        "owing to the fact that": "because",
        "for the reason that": "because",
        "on account of the fact that": "because",
        "by reason of the fact that": "because",
        "in view of the fact that": "because",
        "considering the fact that": "since",
        "given the fact that": "since",
        "seeing that": "since",
        "inasmuch as": "since",
        "insofar as": "since",
        "in the event that": "if",
        "in the case that": "if",
        "under the circumstances that": "if",
        "provided that": "if",
        "on the condition that": "if",
        "assuming that": "if",
        "supposing that": "if",
        "granted that": "if",
        "in the instance that": "if",
        "at the present time": "now",
        "at this point in time": "now",
        "at the current time": "now",
        "at the moment": "now",
        "as of now": "now",
        "as things stand": "now",
        "for the time being": "now",
        "at present": "now",
        "presently": "now",
        "currently": "now",
        "at this juncture": "now",
        "in order to": "to",
        "for the purpose of": "to",
        "with the intention of": "to",
        "with a view to": "to",
        "so as to": "to",
        "with the aim of": "to",
        "with the goal of": "to",
        "with the objective of": "to",
        "by means of": "by",
        "through the use of": "by",
        "by way of": "by",
        "via": "by",
        "by virtue of": "by",
        "by dint of": "by",
        "with regard to": "about",
        "with respect to": "about",
        "in regard to": "about",
        "in respect to": "about",
        "as regards": "about",
        "as for": "about",
        "concerning": "about",
        "regarding": "about",
        "relating to": "about",
        "pertaining to": "about",
        "with reference to": "about",
        "in reference to": "about",
        "in connection with": "about",
        "in relation to": "about",
        "on the subject of": "about",
        "on the matter of": "about",
        "touching on": "about",
        "dealing with": "about",
        "prior to": "before",
        "previous to": "before",
        "in advance of": "before",
        "ahead of": "before",
        "preceding": "before",
        "subsequent to": "after",
        "following": "after",
        "in the aftermath of": "after",
        "in the wake of": "after",
        "as a result of": "because of",
        "as a consequence of": "because of",
        "by reason of": "because of",
        "on account of": "because of",
        "owing to": "because of",
        "thanks to": "because of",
        "in light of": "because of",
        "in view of": "because of",
        "considering": "because of",
        "given": "because of",
        "seeing": "because of",
        "in the near future": "soon",
        "in the not-too-distant future": "soon",
        "before long": "soon",
        "in a short while": "soon",
        "shortly": "soon",
        "presently": "soon",
        "momentarily": "soon",
        "in a moment": "soon",
        "in a minute": "soon",
        "any minute now": "soon",
        "any day now": "soon",
        "a large number of": "many",
        "a great number of": "many",
        "a considerable number of": "many",
        "numerous": "many",
        "countless": "many",
        "a multitude of": "many",
        "a plethora of": "many",
        "an abundance of": "many",
        "a wealth of": "many",
        "a host of": "many",
        "a majority of": "most",
        "the majority of": "most",
        "the greater part of": "most",
        "the bulk of": "most",
        "a minority of": "few",
        "a small number of": "few",
        "a handful of": "few",
        "a couple of": "two",
        "a pair of": "two",
        "has the ability to": "can",
        "is able to": "can",
        "is capable of": "can",
        "has the capacity to": "can",
        "is in a position to": "can",
        "make use of": "use",
        "put to use": "use",
        "employ": "use",
        "utilize": "use",
        "avail oneself of": "use",
        "take advantage of": "use",
        "take into consideration": "consider",
        "give consideration to": "consider",
        "take into account": "consider",
        "bear in mind": "consider",
        "keep in mind": "consider",
        "be mindful of": "consider",
        "pay attention to": "consider",
        "give thought to": "consider",
        "think about": "consider",
        "reflect on": "consider",
        "contemplate": "consider",
        "ponder": "consider",
        "deliberate on": "consider",
        "weigh": "consider",
        "mull over": "consider"
    },

    // Shortening replacements (200+ entries)
    shorten: {
        // Time expressions
        "at this point in time": "now",
        "at the present time": "now",
        "at the current time": "now",
        "at this moment in time": "now",
        "at this juncture": "now",
        "as of this moment": "now",
        "as things stand now": "now",
        "for the time being": "now",
        "in the here and now": "now",
        "in the present day": "now",
        "in today's world": "now",
        "in this day and age": "now",
        "in the near future": "soon",
        "in the not-too-distant future": "soon",
        "at some point in the future": "later",
        "at a later date": "later",
        "at a future time": "later",
        "in days to come": "later",
        "in times to come": "later",
        "down the road": "later",
        "further down the line": "later",
        "prior to": "before",
        "previous to": "before",
        "in advance of": "before",
        "ahead of time": "early",
        "subsequent to": "after",
        "following": "after",
        "in the aftermath of": "after",
        "in the wake of": "after",
        
        // Purpose and reason
        "in order to": "to",
        "for the purpose of": "to",
        "with the intention of": "to",
        "with the aim of": "to",
        "with the goal of": "to",
        "with the objective of": "to",
        "with a view to": "to",
        "so as to": "to",
        "in an effort to": "to",
        "in an attempt to": "to",
        "for the sake of": "for",
        "on behalf of": "for",
        "in the interest of": "for",
        "due to the fact that": "because",
        "owing to the fact that": "because",
        "for the reason that": "because",
        "on account of the fact that": "because",
        "by reason of the fact that": "because",
        "in view of the fact that": "because",
        "considering the fact that": "since",
        "given the fact that": "since",
        "in light of the fact that": "since",
        "as a result of the fact that": "because",
        "as a consequence of the fact that": "because",
        
        // Conditional expressions
        "in the event that": "if",
        "in the case that": "if",
        "under the circumstances that": "if",
        "in the instance that": "if",
        "on the condition that": "if",
        "provided that": "if",
        "assuming that": "if",
        "supposing that": "if",
        "granted that": "if",
        "in the situation where": "if",
        "under the assumption that": "if",
        
        // Contrast and concession
        "in spite of the fact that": "although",
        "despite the fact that": "although",
        "notwithstanding the fact that": "although",
        "regardless of the fact that": "although",
        "even though": "although",
        "on the other hand": "however",
        "by contrast": "however",
        "in contrast": "however",
        "conversely": "however",
        "nevertheless": "however",
        "nonetheless": "however",
        "be that as it may": "however",
        "having said that": "however",
        "that being said": "however",
        
        // Methods and means
        "by means of": "by",
        "through the use of": "by",
        "by way of": "by",
        "by virtue of": "by",
        "by dint of": "by",
        "with the help of": "using",
        "with the aid of": "using",
        "with the assistance of": "using",
        "through the medium of": "through",
        "via the medium of": "through",
        
        // Reference and relation
        "with regard to": "about",
        "with respect to": "about",
        "in regard to": "about",
        "in respect to": "about",
        "as regards": "about",
        "as for": "about",
        "concerning": "about",
        "regarding": "about",
        "relating to": "about",
        "pertaining to": "about",
        "with reference to": "about",
        "in reference to": "about",
        "in connection with": "about",
        "in relation to": "about",
        "on the subject of": "about",
        "on the matter of": "about",
        "touching on": "about",
        "dealing with": "about",
        "in terms of": "regarding",
        "from the standpoint of": "regarding",
        "from the perspective of": "regarding",
        "from the point of view of": "regarding",
        
        // Quantity expressions
        "a large number of": "many",
        "a great number of": "many",
        "a considerable number of": "many",
        "a substantial number of": "many",
        "a significant number of": "many",
        "numerous": "many",
        "countless": "many",
        "a multitude of": "many",
        "a plethora of": "many",
        "an abundance of": "many",
        "a wealth of": "many",
        "a host of": "many",
        "loads of": "many",
        "tons of": "many",
        "heaps of": "many",
        "piles of": "many",
        "stacks of": "many",
        "bunches of": "many",
        "scores of": "many",
        "dozens of": "many",
        "a majority of": "most",
        "the majority of": "most",
        "the greater part of": "most",
        "the bulk of": "most",
        "a minority of": "few",
        "a small number of": "few",
        "a handful of": "few",
        "a couple of": "two",
        "a pair of": "two",
        "each and every": "every",
        "one and all": "everyone",
        "all and sundry": "everyone",
        
        // Ability and capability
        "has the ability to": "can",
        "is able to": "can",
        "is capable of": "can",
        "has the capacity to": "can",
        "is in a position to": "can",
        "has the power to": "can",
        "is empowered to": "can",
        "is authorized to": "can",
        "is permitted to": "may",
        "is allowed to": "may",
        "has permission to": "may",
        "has the right to": "may",
        "is entitled to": "may",
        
        // Usage and employment
        "make use of": "use",
        "put to use": "use",
        "employ": "use",
        "utilize": "use",
        "avail oneself of": "use",
        "take advantage of": "use",
        "resort to": "use",
        "have recourse to": "use",
        "turn to": "use",
        "fall back on": "use",
        
        // Consideration and thought
        "take into consideration": "consider",
        "give consideration to": "consider",
        "take into account": "consider",
        "take account of": "consider",
        "bear in mind": "consider",
        "keep in mind": "consider",
        "be mindful of": "consider",
        "pay attention to": "consider",
        "give thought to": "consider",
        "think about": "consider",
        "reflect on": "consider",
        "contemplate": "consider",
        "ponder": "consider",
        "deliberate on": "consider",
        "weigh": "consider",
        "mull over": "consider",
        "chew over": "consider",
        "sleep on": "consider",
        
        // Decision and choice
        "make a decision": "decide",
        "come to a decision": "decide",
        "reach a decision": "decide",
        "arrive at a decision": "decide",
        "make a choice": "choose",
        "make a selection": "select",
        "opt for": "choose",
        "settle on": "choose",
        "go with": "choose",
        "pick out": "select",
        "single out": "select",
        
        // Communication and expression
        "express the opinion that": "think",
        "be of the opinion that": "think",
        "hold the view that": "think",
        "take the view that": "think",
        "be of the view that": "think",
        "maintain that": "say",
        "assert that": "say",
        "declare that": "say",
        "state that": "say",
        "claim that": "say",
        "contend that": "argue",
        "argue that": "argue",
        "suggest that": "suggest",
        "propose that": "propose",
        "recommend that": "recommend",
        "advise that": "advise",
        
        // Location and position
        "in the vicinity of": "near",
        "in the neighborhood of": "near",
        "in close proximity to": "near",
        "adjacent to": "next to",
        "in the immediate vicinity of": "near",
        "within the vicinity of": "near",
        "in the area of": "near",
        "in the region of": "near",
        "somewhere in the region of": "about",
        "somewhere in the vicinity of": "about",
        "somewhere around": "about",
        "in the ballpark of": "about",
        
        // Frequency and occurrence
        "on a regular basis": "regularly",
        "on a frequent basis": "frequently",
        "on an occasional basis": "occasionally",
        "from time to time": "sometimes",
        "every now and then": "sometimes",
        "every so often": "sometimes",
        "once in a while": "sometimes",
        "at regular intervals": "regularly",
        "at frequent intervals": "frequently",
        "at irregular intervals": "irregularly",
        
        // Degree and extent
        "to a great extent": "greatly",
        "to a large extent": "largely",
        "to a considerable extent": "considerably",
        "to a significant extent": "significantly",
        "to some extent": "somewhat",
        "to a certain extent": "somewhat",
        "to a limited extent": "slightly",
        "to a small extent": "slightly",
        "in large measure": "largely",
        "in great measure": "greatly",
        "for the most part": "mostly",
        "by and large": "generally",
        "on the whole": "generally",
        "all in all": "overall",
        "all things considered": "overall",
        "taking everything into account": "overall",
        "when all is said and done": "ultimately"
    },

    // Filler words to remove (for shortening) (100+ entries)
    fillerWords: [
        // Process and progression
        "in the process of",
        "in the course of",
        "in the act of",
        "in the midst of",
        "during the course of",
        "throughout the course of",
        "over the course of",
        "in the span of",
        "within the span of",
        "for the duration of",
        "throughout the duration of",
        
        // Hedging and uncertainty
        "basically",
        "essentially",
        "fundamentally",
        "primarily",
        "mainly",
        "chiefly",
        "principally",
        "largely",
        "mostly",
        "generally",
        "typically",
        "usually",
        "normally",
        "ordinarily",
        "commonly",
        "frequently",
        "often",
        "regularly",
        "consistently",
        "constantly",
        "continually",
        "continuously",
        "perpetually",
        "invariably",
        "always",
        "never",
        "rarely",
        "seldom",
        "occasionally",
        "sometimes",
        "perhaps",
        "maybe",
        "possibly",
        "probably",
        "likely",
        "presumably",
        "supposedly",
        "allegedly",
        "apparently",
        "seemingly",
        "evidently",
        "obviously",
        "clearly",
        "certainly",
        "definitely",
        "absolutely",
        "positively",
        "undoubtedly",
        "unquestionably",
        "indubitably",
        "without a doubt",
        "beyond a doubt",
        "no doubt",
        "doubtless",
        "undeniably",
        "incontrovertibly",
        "irrefutably",
        "categorically",
        "emphatically",
        "decidedly",
        "distinctly",
        "markedly",
        "notably",
        "particularly",
        "especially",
        "specifically",
        "precisely",
        "exactly",
        "literally",
        "virtually",
        "practically",
        "effectively",
        "essentially",
        "basically",
        
        // Intensifiers
        "actually",
        "really",
        "truly",
        "genuinely",
        "honestly",
        "frankly",
        "seriously",
        "literally",
        "totally",
        "completely",
        "entirely",
        "wholly",
        "fully",
        "thoroughly",
        "utterly",
        "absolutely",
        "perfectly",
        "extremely",
        "incredibly",
        "amazingly",
        "surprisingly",
        "remarkably",
        "exceptionally",
        "extraordinarily",
        "tremendously",
        "enormously",
        "immensely",
        "vastly",
        "hugely",
        "massively",
        "significantly",
        "considerably",
        "substantially",
        "materially",
        "noticeably",
        "appreciably",
        "markedly",
        "distinctly",
        "decidedly",
        "definitely",
        "certainly",
        "surely",
        "undoubtedly",
        "unquestionably",
        "indisputably",
        "undeniably",
        "incontestably",
        "irrefutably",
        "beyond question",
        "without question",
        "beyond doubt",
        "without doubt",
        "no doubt",
        "doubtless",
        "assuredly",
        "positively",
        "categorically",
        "emphatically",
        "unequivocally",
        "unconditionally",
        "unreservedly",
        "wholeheartedly",
        "enthusiastically",
        "eagerly",
        "keenly",
        "ardently",
        "fervently",
        "passionately",
        "intensely",
        "deeply",
        "profoundly",
        "thoroughly",
        "completely",
        "totally",
        "utterly",
        "entirely",
        "wholly",
        "fully",
        "quite",
        "rather",
        "fairly",
        "reasonably",
        "moderately",
        "somewhat",
        "slightly",
        "marginally",
        "minimally",
        "barely",
        "hardly",
        "scarcely",
        "just",
        "only",
        "merely",
        "simply",
        "purely",
        "solely",
        "exclusively",
        "uniquely",
        "particularly",
        "especially",
        "specifically",
        "notably",
        "remarkably",
        "exceptionally",
        "unusually",
        "uncommonly",
        "extraordinarily",
        "incredibly",
        "unbelievably",
        "amazingly",
        "astonishingly",
        "surprisingly",
        "shockingly",
        "stunningly",
        "breathtakingly",
        "spectacularly",
        "magnificently",
        "splendidly",
        "wonderfully",
        "marvelously",
        "fantastically",
        "fabulously",
        "tremendously",
        "enormously",
        "immensely",
        "vastly",
        "hugely",
        "massively",
        "colossally",
        "monumentally",
        "astronomically",
        "phenomenally",
        "prodigiously",
        "stupendously",
        "mind-bogglingly",
        "jaw-droppingly",
        "eye-poppingly",
        "heart-stoppingly",
        "breath-takingly",
        "awe-inspiringly",
        "spine-tinglingly",
        "hair-raisingly",
        "bone-chillingly",
        "blood-curdlingly",
        "nerve-wrackingly",
        "gut-wrenchingly",
        "heart-wrenchingly",
        "soul-stirringly",
        "mind-blowingly",
        "earth-shatteringly",
        "ground-breakingly",
        "trail-blazingly",
        "trend-settingly",
        "pace-settingly",
        "record-breakingly",
        "history-makingly",
        "epoch-makingly",
        "world-changingly",
        "life-changingly",
        "game-changingly",
        "paradigm-shiftingly",
        
        // Qualifiers and hedges
        "very",
        "pretty",
        "sort of",
        "kind of",
        "type of",
        "style of",
        "manner of",
        "way of",
        "form of",
        "version of",
        "variant of",
        "variation of",
        "modification of",
        "adaptation of",
        "interpretation of",
        "rendition of",
        "representation of",
        "manifestation of",
        "expression of",
        "demonstration of",
        "illustration of",
        "example of",
        "instance of",
        "case of",
        "occurrence of",
        "happening of",
        "event of",
        "situation of",
        "circumstance of",
        "condition of",
        "state of",
        "status of",
        "position of",
        "stance of",
        "attitude of",
        "approach of",
        "method of",
        "technique of",
        "procedure of",
        "process of",
        "system of",
        "mechanism of",
        "means of",
        "way of",
        "mode of",
        "fashion of",
        "style of",
        "manner of",
        
        // Opinion markers
        "in my opinion",
        "in my view",
        "in my estimation",
        "in my judgment",
        "in my assessment",
        "in my evaluation",
        "from my perspective",
        "from my standpoint",
        "from my point of view",
        "as I see it",
        "as I understand it",
        "as I perceive it",
        "as far as I'm concerned",
        "as far as I can tell",
        "as far as I know",
        "to my knowledge",
        "to my understanding",
        "to the best of my knowledge",
        "to the best of my understanding",
        "if I'm not mistaken",
        "if I remember correctly",
        "if memory serves",
        "I think that",
        "I believe that",
        "I feel that",
        "I suppose that",
        "I imagine that",
        "I assume that",
        "I presume that",
        "I suspect that",
        "I reckon that",
        "I figure that",
        "I guess that",
        "I would say that",
        "I would think that",
        "I would imagine that",
        "I would suppose that",
        "I would assume that",
        "I would presume that",
        "I would suspect that",
        "I would reckon that",
        "I would figure that",
        "I would guess that",
        "it seems that",
        "it appears that",
        "it looks like",
        "it sounds like",
        "it feels like",
        "it strikes me that",
        "it occurs to me that",
        "it comes to mind that",
        "it crosses my mind that",
        "the fact is that",
        "the truth is that",
        "the reality is that",
        "the point is that",
        "the thing is that",
        "what I mean is that",
        "what I'm saying is that",
        "what I'm getting at is that",
        "what I'm driving at is that",
        "what I'm trying to say is that",
        "the way I see it",
        "the way I look at it",
        "the way I figure it",
        "the way I understand it",
        "if you ask me",
        "if you want my opinion",
        "speaking for myself",
        "personally speaking",
        "for my part",
        "as for me",
        "as for myself"
    ]
};

// Export for use in main script
if (typeof module !== 'undefined' && module.exports) {
    module.exports = GRAMMAR_DATA;
}
